name: Clone Base Branch
description: Clone the PR base branch in addition to the target branch
author: https://github.com/therealbnut
requirements: ['git']
configuration:
  properties:
    checkout_path:
      type: string
    branch:
      type: string
    subpath:
      type: string
  additionalProperties: false
